[package]
name = "lorenz-field-2d"
version = "0.1.0"
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15"
nalgebra = "0.19.0"
num-traits = "0.2.10"